[project]
name = "cosorikettleble"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.13.0"
dependencies = [
    "esphome>=2025.12.3",
    "pip>=25.3",
]
